services:
  portfolio:
    container_name: portfolio
    build:
      context: .
    env_file:
      - .env
    networks:
      - container-dmz
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`roymond.net`)||Host(`www.roymond.net`)"
      - "traefik.http.routers.portfolio.entrypoints=https"
      - "traefik.http.routers.portfolio.middlewares=default@file"
      - "traefik.http.routers.portfolio.tls.certresolver=letsEncrypt"
      - "traefik.http.services.portfolio.loadbalancer.server.port=5550"
    ports:
      - "5550:5550"
    volumes:
      - ./src:/src
      - ./public:/public
    restart: always

networks:
  container-dmz:
    external: true
